name: testovy_zadanie4
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  lottie: ^2.4.0
  dio: 5.1.1
  shared_preferences: ^2.1.0
  mask_text_input_formatter: ^2.4.0
  flutter_secure_storage: ^7.0.1
  go_router: ^7.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_riverpod: ^2.3.6
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/vector/
    - assets/lottie/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope.ttf
    - family: ManropeVariable
      fonts:
        - asset: assets/font/Manrope_VariableFont.ttf

flutter_intl:
  enabled: true
